# Support the author by using the funding links below
# github sponsors: https://github.com/sponsors/merlinbecker
# Buy me a coffee: https://buymeacoffee.com/merlinbecker

github: merlinbecker
buy_me_a_coffee: merlinbecker